import crypto from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import AdmZip from 'adm-zip'
import { PNG } from 'pngjs'

const VERSION = process.env.MC_VERSION ?? '26.2'
const MANIFEST_URL =
  'https://piston-meta.mojang.com/mc/game/version_manifest_v2.json'
const OUT_FILE = new URL('../src/generated/survivalMixedPalette.js', import.meta.url)
const CACHE_DIR = new URL('../.cache/minecraft-assets/', import.meta.url)
const DIRECTIONS = ['down', 'up', 'north', 'south', 'west', 'east']
const DIRECTION_PROPERTIES = new Set(DIRECTIONS)

const LEGACY_WOOL = {
  white: 0,
  orange: 1,
  magenta: 2,
  light_blue: 3,
  yellow: 4,
  lime: 5,
  pink: 6,
  gray: 7,
  light_gray: 8,
  cyan: 9,
  purple: 10,
  blue: 11,
  brown: 12,
  green: 13,
  red: 14,
  black: 15,
}

const LEGACY_COLORS = [
  ['white', [234, 236, 237]],
  ['orange', [241, 118, 20]],
  ['magenta', [189, 68, 179]],
  ['light_blue', [58, 175, 217]],
  ['yellow', [248, 198, 39]],
  ['lime', [112, 185, 25]],
  ['pink', [237, 141, 172]],
  ['gray', [62, 68, 71]],
  ['light_gray', [142, 142, 134]],
  ['cyan', [21, 137, 145]],
  ['purple', [121, 42, 172]],
  ['blue', [53, 57, 157]],
  ['brown', [114, 71, 40]],
  ['green', [84, 109, 27]],
  ['red', [161, 39, 34]],
  ['black', [20, 21, 25]],
]

const GRAVITY_BLOCKS = new Set([
  'sand',
  'red_sand',
  'gravel',
  'suspicious_sand',
  'suspicious_gravel',
])

const PREFERRED_VALUES = {
  axis: 'y',
  facing: 'north',
  horizontal_facing: 'north',
  half: 'lower',
  type: 'single',
  shape: 'straight',
  age: '0',
  stage: '0',
  level: '0',
  power: '0',
  rotation: '0',
  charges: '0',
  delay: '1',
  lit: 'false',
  powered: 'false',
  triggered: 'false',
  open: 'false',
  waterlogged: 'false',
  snowy: 'false',
  occupied: 'false',
  enabled: 'true',
  persistent: 'true',
}

const TINTS = {
  grass_block: [91, 145, 59],
  oak_leaves: [72, 112, 41],
  jungle_leaves: [72, 112, 41],
  acacia_leaves: [72, 112, 41],
  dark_oak_leaves: [72, 112, 41],
  mangrove_leaves: [72, 112, 41],
  pale_oak_leaves: [87, 112, 77],
  azalea_leaves: [72, 112, 41],
  flowering_azalea_leaves: [84, 119, 49],
  birch_leaves: [128, 167, 85],
  spruce_leaves: [97, 153, 97],
}

await fs.mkdir(CACHE_DIR, { recursive: true })
const { zip, dataVersion } = await loadClientJar(VERSION)
const entries = new Map(zip.getEntries().map((entry) => [entry.entryName, entry]))
const textureCache = new Map()
const modelCache = new Map()
const obtainableItems = collectObtainableItems()
const blockNames = [...entries.keys()]
  .filter((name) => /^assets\/minecraft\/blockstates\/[^/]+\.json$/.test(name))
  .map((name) => path.basename(name, '.json'))
  .sort()

const generated = []

for (const blockName of blockNames) {
  if (!entries.has(`assets/minecraft/items/${blockName}.json`)) continue
  if (!obtainableItems.has(`minecraft:${blockName}`)) continue

  const blockState = readJson(`assets/minecraft/blockstates/${blockName}.json`)
  const selection = selectBlockState(blockState)
  if (!selection || selection.applications.length === 0) continue

  const faces = analyzeBlockFaces(blockName, selection.applications)
  if (!faces) continue

  const faceRgb = Object.fromEntries(
    DIRECTIONS.map((direction) => [direction, faces[direction].rgb]),
  )
  const faceSpread = Object.fromEntries(
    DIRECTIONS.map((direction) => [direction, faces[direction].spread]),
  )
  const faceAlpha = Object.fromEntries(
    DIRECTIONS.map((direction) => [direction, faces[direction].alpha]),
  )
  const rgb = averageColors(Object.values(faceRgb))

  generated.push({
    key: blockName,
    label: title(blockName),
    state: blockStateName(blockName, selection.properties),
    rgb,
    faceRgb,
    faceSpread,
    faceAlpha,
    legacyId: 35,
    legacyData: nearestLegacy(rgb),
    unstable:
      GRAVITY_BLOCKS.has(blockName) ||
      blockName.endsWith('_concrete_powder') ||
      blockName.endsWith('_coral_block'),
  })
}

const output = `// Generated by scripts/generateSurvivalMixedPalette.mjs from official Minecraft ${VERSION} client assets.
// Contains survival-obtainable blocks whose selected state covers every face of a full voxel.
export const SURVIVAL_MIXED_VERSION = ${JSON.stringify(VERSION)}
export const SURVIVAL_MIXED_DATA_VERSION = ${dataVersion}
export const SURVIVAL_MIXED_BLOCKS = ${JSON.stringify(generated, null, 2)}
`

await fs.writeFile(OUT_FILE, output)
console.log(
  `Generated ${generated.length} face-aware survival blocks for Minecraft ${VERSION} (DataVersion ${dataVersion}).`,
)

async function loadClientJar(version) {
  const manifest = await fetchJson(MANIFEST_URL)
  const versionEntry = manifest.versions.find((entry) => entry.id === version)
  if (!versionEntry) throw new Error(`Minecraft ${version} was not found.`)

  const metadata = await fetchJson(versionEntry.url)
  const download = metadata.downloads.client
  const cachePath = fileURLToPath(new URL(`${version}-client.jar`, CACHE_DIR))
  let jarBuffer = null

  try {
    const cached = await fs.readFile(cachePath)
    if (sha1(cached) === download.sha1) jarBuffer = cached
  } catch {
    // The cache is optional.
  }

  if (!jarBuffer) {
    console.log(`Downloading official Minecraft ${version} client assets...`)
    const response = await fetch(download.url)
    if (!response.ok) throw new Error(`Client download failed: ${response.status}`)
    jarBuffer = Buffer.from(await response.arrayBuffer())
    if (sha1(jarBuffer) !== download.sha1) {
      throw new Error('Downloaded Minecraft client checksum did not match.')
    }
    await fs.writeFile(cachePath, jarBuffer)
  }

  const clientZip = new AdmZip(jarBuffer)
  const versionJson = JSON.parse(
    clientZip.readAsText(clientZip.getEntry('version.json')),
  )
  return { zip: clientZip, dataVersion: versionJson.world_version }
}

async function fetchJson(url) {
  const response = await fetch(url)
  if (!response.ok) throw new Error(`Request failed (${response.status}): ${url}`)
  return response.json()
}

function sha1(value) {
  return crypto.createHash('sha1').update(value).digest('hex')
}

function collectObtainableItems() {
  const ids = new Set()
  for (const [entryName, entry] of entries) {
    if (/^data\/minecraft\/recipe\/.*\.json$/.test(entryName)) {
      const json = JSON.parse(entry.getData().toString('utf8'))
      if (typeof json.result?.id === 'string') ids.add(json.result.id)
    } else if (/^data\/minecraft\/loot_table\/blocks\/.*\.json$/.test(entryName)) {
      const json = JSON.parse(entry.getData().toString('utf8'))
      collectLootItems(json, ids)
    }
  }
  return ids
}

function collectLootItems(value, ids) {
  if (Array.isArray(value)) {
    for (const item of value) collectLootItems(item, ids)
    return
  }
  if (!value || typeof value !== 'object') return
  if (value.type === 'minecraft:item' && typeof value.name === 'string') {
    ids.add(value.name)
  }
  for (const child of Object.values(value)) collectLootItems(child, ids)
}

function selectBlockState(blockState) {
  if (blockState.variants) {
    const candidates = []
    for (const [key, value] of Object.entries(blockState.variants)) {
      const properties = parseProperties(key)
      for (const application of asArray(value)) {
        candidates.push({
          properties,
          applications: [application],
          score: propertyScore(properties) + rotationScore(application),
        })
      }
    }
    return candidates.sort((a, b) => a.score - b.score)[0] ?? null
  }

  if (!blockState.multipart) return null
  const propertyValues = new Map()
  for (const part of blockState.multipart) {
    collectConditionValues(part.when, propertyValues)
  }
  const properties = {}
  const hasAllDirections = DIRECTIONS.every((name) => propertyValues.has(name))
  for (const [name, values] of propertyValues) {
    properties[name] = preferredValue(name, [...values], hasAllDirections)
  }

  const applications = []
  for (const part of blockState.multipart) {
    if (!matchesCondition(part.when, properties)) continue
    const choices = asArray(part.apply).sort(
      (a, b) => rotationScore(a) - rotationScore(b),
    )
    if (choices[0]) applications.push(choices[0])
  }
  return { properties, applications }
}

function parseProperties(key) {
  if (!key) return {}
  return Object.fromEntries(key.split(',').map((entry) => entry.split('=')))
}

function propertyScore(properties) {
  let score = 0
  for (const [name, value] of Object.entries(properties)) {
    const preferred = PREFERRED_VALUES[name]
    if (preferred !== undefined && value !== preferred) score += 12
    if (value === 'true' && /(lit|powered|open|triggered|occupied)/.test(name)) {
      score += 8
    }
  }
  return score
}

function rotationScore(application) {
  return (application.x ? 2 : 0) + (application.y ? 1 : 0)
}

function collectConditionValues(condition, target) {
  if (!condition || typeof condition !== 'object') return
  for (const [key, value] of Object.entries(condition)) {
    if (key === 'OR' || key === 'AND') {
      for (const child of asArray(value)) collectConditionValues(child, target)
      continue
    }
    const values = target.get(key) ?? new Set()
    for (const option of String(value).split('|')) values.add(option)
    target.set(key, values)
  }
}

function preferredValue(name, values, hasAllDirections) {
  if (hasAllDirections && DIRECTION_PROPERTIES.has(name) && values.includes('true')) {
    return 'true'
  }
  if (/^slot_\d+_occupied$/.test(name) && values.includes('false')) return 'false'
  const preferred = PREFERRED_VALUES[name]
  if (preferred !== undefined && values.includes(preferred)) return preferred
  if (values.includes('false')) return 'false'
  if (values.includes('0')) return '0'
  return values.sort()[0]
}

function matchesCondition(condition, properties) {
  if (!condition) return true
  if (condition.OR) return condition.OR.some((child) => matchesCondition(child, properties))
  if (condition.AND) return condition.AND.every((child) => matchesCondition(child, properties))
  return Object.entries(condition).every(([name, values]) =>
    String(values).split('|').includes(properties[name]),
  )
}

function analyzeBlockFaces(blockName, applications) {
  const canvases = Object.fromEntries(
    DIRECTIONS.map((direction) => [direction, createFaceCanvas()]),
  )

  for (const application of applications) {
    const model = resolveModel(application.model)
    if (!model?.elements) continue

    for (const element of model.elements) {
      for (const [sourceDirection, face] of Object.entries(element.faces ?? {})) {
        if (!DIRECTIONS.includes(sourceDirection)) continue
        if (!isBoundaryFace(sourceDirection, element, face)) continue

        const targetDirection = rotateDirection(
          sourceDirection,
          application.x ?? 0,
          application.y ?? 0,
        )
        const textureName = resolveTextureName(face.texture, model.textures)
        const texture = loadTexture(textureName)
        if (!texture) continue
        paintFace(
          canvases[targetDirection],
          texture,
          element,
          sourceDirection,
          face,
          face.tintindex === undefined ? null : TINTS[blockName] ?? [104, 160, 74],
        )
      }
    }
  }

  const result = {}
  for (const direction of DIRECTIONS) {
    const stats = analyzeCanvas(canvases[direction])
    if (!stats || stats.geometryCoverage < 0.995) return null
    result[direction] = stats
  }
  return result
}

function resolveModel(modelReference) {
  const name = normalizeResource(modelReference, 'block')
  if (!name) return null
  if (modelCache.has(name)) return modelCache.get(name)

  const json = readJson(`assets/minecraft/models/${name}.json`)
  if (!json) return null
  const parent = json.parent ? resolveModel(json.parent) : null
  const resolved = {
    textures: { ...(parent?.textures ?? {}), ...(json.textures ?? {}) },
    elements: json.elements ?? parent?.elements ?? [],
  }
  modelCache.set(name, resolved)
  return resolved
}

function resolveTextureName(reference, textures) {
  let value = reference
  const seen = new Set()
  while (typeof value === 'string' && value.startsWith('#') && !seen.has(value)) {
    seen.add(value)
    value = textures[value.slice(1)]
  }
  if (value && typeof value === 'object') value = value.sprite
  if (typeof value !== 'string') return null
  return normalizeResource(value, 'block')
}

function normalizeResource(value, defaultFolder) {
  if (!value) return null
  const withoutNamespace = value.replace(/^minecraft:/, '')
  return withoutNamespace.includes('/')
    ? withoutNamespace
    : `${defaultFolder}/${withoutNamespace}`
}

function loadTexture(name) {
  if (!name) return null
  if (textureCache.has(name)) return textureCache.get(name)
  const entry = entries.get(`assets/minecraft/textures/${name}.png`)
  if (!entry) return null
  const png = PNG.sync.read(entry.getData())
  textureCache.set(name, png)
  return png
}

function createFaceCanvas() {
  return {
    pixels: Array.from({ length: 256 }, () => [0, 0, 0, 0]),
    geometry: new Uint8Array(256),
  }
}

function paintFace(canvas, texture, element, direction, face, tint) {
  const bounds = projectedBounds(element, direction)
  const x1 = Math.max(0, Math.floor(bounds[0]))
  const y1 = Math.max(0, Math.floor(bounds[1]))
  const x2 = Math.min(16, Math.ceil(bounds[2]))
  const y2 = Math.min(16, Math.ceil(bounds[3]))
  const uv = face.uv ?? [0, 0, 16, 16]
  const frameSize = Math.min(texture.width, texture.height)

  for (let y = y1; y < y2; y += 1) {
    for (let x = x1; x < x2; x += 1) {
      const index = y * 16 + x
      canvas.geometry[index] = 1
      const tx = Math.min(
        texture.width - 1,
        Math.max(0, Math.floor(((uv[0] + ((x - x1 + 0.5) / Math.max(1, x2 - x1)) * (uv[2] - uv[0])) / 16) * texture.width)),
      )
      const ty = Math.min(
        frameSize - 1,
        Math.max(0, Math.floor(((uv[1] + ((y - y1 + 0.5) / Math.max(1, y2 - y1)) * (uv[3] - uv[1])) / 16) * frameSize)),
      )
      const textureIndex = (ty * texture.width + tx) * 4
      const source = [
        texture.data[textureIndex],
        texture.data[textureIndex + 1],
        texture.data[textureIndex + 2],
        texture.data[textureIndex + 3],
      ]
      if (tint) {
        source[0] = Math.round((source[0] * tint[0]) / 255)
        source[1] = Math.round((source[1] * tint[1]) / 255)
        source[2] = Math.round((source[2] * tint[2]) / 255)
      }
      canvas.pixels[index] = alphaComposite(source, canvas.pixels[index])
    }
  }
}

function projectedBounds(element, direction) {
  const from = element.from ?? [0, 0, 0]
  const to = element.to ?? [16, 16, 16]
  if (direction === 'up' || direction === 'down') return [from[0], from[2], to[0], to[2]]
  if (direction === 'east' || direction === 'west') return [from[2], 16 - to[1], to[2], 16 - from[1]]
  return [from[0], 16 - to[1], to[0], 16 - from[1]]
}

function isBoundaryFace(direction, element, face) {
  if (face.cullface) return true
  const from = element.from ?? [0, 0, 0]
  const to = element.to ?? [16, 16, 16]
  return (
    (direction === 'down' && from[1] === 0) ||
    (direction === 'up' && to[1] === 16) ||
    (direction === 'north' && from[2] === 0) ||
    (direction === 'south' && to[2] === 16) ||
    (direction === 'west' && from[0] === 0) ||
    (direction === 'east' && to[0] === 16)
  )
}

function rotateDirection(direction, xRotation, yRotation) {
  let result = direction
  for (let turns = 0; turns < ((xRotation % 360) + 360) % 360 / 90; turns += 1) {
    result = { north: 'down', down: 'south', south: 'up', up: 'north' }[result] ?? result
  }
  for (let turns = 0; turns < ((yRotation % 360) + 360) % 360 / 90; turns += 1) {
    result = { north: 'east', east: 'south', south: 'west', west: 'north' }[result] ?? result
  }
  return result
}

function analyzeCanvas(canvas) {
  const geometryCount = canvas.geometry.reduce((sum, value) => sum + value, 0)
  if (geometryCount === 0) return null
  let r = 0
  let g = 0
  let b = 0
  let alphaWeight = 0

  for (const pixel of canvas.pixels) {
    const alpha = pixel[3] / 255
    r += pixel[0] * alpha
    g += pixel[1] * alpha
    b += pixel[2] * alpha
    alphaWeight += alpha
  }

  if (alphaWeight === 0) return null
  const rgb = [
    Math.round(r / alphaWeight),
    Math.round(g / alphaWeight),
    Math.round(b / alphaWeight),
  ]
  let spread = 0
  for (const pixel of canvas.pixels) {
    const alpha = pixel[3] / 255
    const dr = pixel[0] - rgb[0]
    const dg = pixel[1] - rgb[1]
    const db = pixel[2] - rgb[2]
    spread += Math.sqrt(dr * dr * 0.3 + dg * dg * 0.59 + db * db * 0.11) * alpha
  }

  return {
    rgb,
    spread: Math.round((spread / alphaWeight) * 10) / 10,
    alpha: Math.round((alphaWeight / 256) * 1000) / 1000,
    geometryCoverage: geometryCount / 256,
  }
}

function alphaComposite(source, destination) {
  const sourceAlpha = source[3] / 255
  const destinationAlpha = destination[3] / 255
  const outputAlpha = sourceAlpha + destinationAlpha * (1 - sourceAlpha)
  if (outputAlpha === 0) return [0, 0, 0, 0]
  return [
    (source[0] * sourceAlpha + destination[0] * destinationAlpha * (1 - sourceAlpha)) / outputAlpha,
    (source[1] * sourceAlpha + destination[1] * destinationAlpha * (1 - sourceAlpha)) / outputAlpha,
    (source[2] * sourceAlpha + destination[2] * destinationAlpha * (1 - sourceAlpha)) / outputAlpha,
    outputAlpha * 255,
  ]
}

function blockStateName(blockName, properties) {
  const values = Object.entries(properties).sort(([a], [b]) => a.localeCompare(b))
  const suffix = values.length
    ? `[${values.map(([name, value]) => `${name}=${value}`).join(',')}]`
    : ''
  return `minecraft:${blockName}${suffix}`
}

function readJson(entryName) {
  const entry = entries.get(entryName)
  return entry ? JSON.parse(entry.getData().toString('utf8')) : null
}

function asArray(value) {
  return Array.isArray(value) ? value : [value]
}

function averageColors(colors) {
  return [0, 1, 2].map((channel) =>
    Math.round(colors.reduce((sum, color) => sum + color[channel], 0) / colors.length),
  )
}

function nearestLegacy(rgb) {
  let best = 'white'
  let bestDistance = Number.POSITIVE_INFINITY
  for (const [name, color] of LEGACY_COLORS) {
    const dr = rgb[0] - color[0]
    const dg = rgb[1] - color[1]
    const db = rgb[2] - color[2]
    const distance = dr * dr * 0.3 + dg * dg * 0.59 + db * db * 0.11
    if (distance < bestDistance) {
      best = name
      bestDistance = distance
    }
  }
  return LEGACY_WOOL[best]
}

function title(value) {
  return value
    .split('_')
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join(' ')
}
